FROM node:10.16-alpine

ENV PATH_APP /home/app/
ENV NAME_APP masterize_backend
ENV FULLPATH ${PATH_APP}${NAME_APP}

WORKDIR $FULLPATH/
COPY . .

WORKDIR $PATH_APP
RUN if [ ! -e ${FULLPATH}/app.js ]; then npx express-generator $NAME_APP ; fi

WORKDIR ${FULLPATH}/

#RUN npm install
#RUN if [ -e $PATH_APP$NAME_APP/package.json ]; then npm start ; fi

EXPOSE 3000
CMD [ "yarn", "start"]

