export const CartActionTypes = {
    TOGGLE_CART_HIDDEN : "TOGGLE_CART_HIDDEN",
    ADD_ITEM : "ADD_ITEM",
    REMOVE_ITEM : "REMOVE_ITEM",
    UPDATE_QTY: "UPDATE_QTY",
    CLEAR_CART: "CLEAR_CART"
}